2024-04-20 18:30:35,878 (20237/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2024-04-20 18:30:35,878 (20237/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-04-20 18:30:35,905 (20237/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/main.py", line 674, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/main.py", line 661, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 181, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 230, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 738, in connect\n    raise ex.with_traceback(None)\npsycopg.OperationalError: connection is bad: No such file or directory\n\tIs the server running locally and accepting connections on that socket?\n'
2024-04-20 18:32:34,875 (20971/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2024-04-20 18:32:34,876 (20971/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-04-20 18:32:35,686 (20971/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/main.py", line 674, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/main.py", line 661, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 181, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 230, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 738, in connect\n    raise ex.with_traceback(None)\npsycopg.OperationalError: connection failed: error received from server in SCRAM exchange: Wrong password\n'
2024-04-20 18:32:53,292 (21119/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2024-04-20 18:32:53,292 (21119/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-04-20 18:34:52,195 (21119/MainThread) pgcli.pgexecute ERROR - sql: 'create dat', error: SyntaxError('syntax error at or near "dat"\nLINE 1: create dat\n               ^')
2024-04-20 18:34:52,214 (21119/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/psycopg/cursor.py", line 737, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "dat"\nLINE 1: create dat\n               ^\n'
2024-04-20 18:35:11,428 (21119/MainThread) pgcli.pgexecute ERROR - sql: 'create database shelf-tst', error: SyntaxError('syntax error at or near "-"\nLINE 1: create database shelf-tst\n                             ^')
2024-04-20 18:35:11,428 (21119/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/psycopg/cursor.py", line 737, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "-"\nLINE 1: create database shelf-tst\n                             ^\n'
2024-04-20 18:35:22,879 (21119/MainThread) pgcli.pgexecute ERROR - sql: 'gra', error: SyntaxError('syntax error at or near "gra"\nLINE 1: gra\n        ^')
2024-04-20 18:35:22,889 (21119/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/psycopg/cursor.py", line 737, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "gra"\nLINE 1: gra\n        ^\n'
2024-04-20 18:35:49,462 (21119/MainThread) pgcli.pgexecute ERROR - sql: 'grant all privileges on database shelftst to shelftst', error: UndefinedObject('role "shelftst" does not exist')
2024-04-20 18:35:49,463 (21119/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/psycopg/cursor.py", line 737, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.UndefinedObject: role "shelftst" does not exist\n'
2024-04-20 18:37:04,661 (22777/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2024-04-20 18:37:04,661 (22777/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-04-20 18:37:05,650 (22777/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/main.py", line 674, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/main.py", line 661, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 181, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 230, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 738, in connect\n    raise ex.with_traceback(None)\npsycopg.OperationalError: connection failed: FATAL:  Tenant or user not found\nconnection to server at "aws-0-eu-west-1.pooler.supabase.com" (52.209.89.87), port 5432 failed: FATAL:  Tenant or user not found\n'
2024-04-20 18:37:14,577 (22841/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2024-04-20 18:37:14,577 (22841/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-04-20 18:37:15,344 (22841/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/main.py", line 674, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/main.py", line 661, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 181, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 230, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 738, in connect\n    raise ex.with_traceback(None)\npsycopg.OperationalError: connection failed: FATAL:  Tenant or user not found\nconnection to server at "aws-0-eu-west-1.pooler.supabase.com" (108.128.216.176), port 5432 failed: FATAL:  Tenant or user not found\n'
